_target_: src.models.basic_module.BasicLitModule
optim: Adam
lr: 0.001
weight_decay: 0.0005
task: phase
use_timm: True

mlp:
  hidden_size: 1024

temporal_cfg:
  type: #GRU LSTM or leave it blank
  hidden_size: 1024
  num_layers: 3
  bidirectional: True
