# @package _global_

# specify here default evaluation configuration
defaults:
  - _self_
  - datamodule: cholect45.yaml # choose the datamodule for evaluation
  - model: triplet_attention.yaml
  - callbacks: default.yaml
  - logger: wandb.yaml
  - trainer: default.yaml
  - log_dir: evaluation.yaml

  - experiment: null

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

original_work_dir: ${hydra:runtime.cwd}

data_dir: ${original_work_dir}/data/CholecT45/

print_config: True

ignore_warnings: True

seed: null

name: "default"

# passing checkpoint path is necessary
ckpt_path: ${original_work_dir}/logs/runs/test/last.ckpt
